### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by haesleinhuepf** [MMV-Lab/VessQC#11]
Hi @PLampen ,

just a minor note: There are some artifacts such as `<<< HEAD` of a failed git merge in the [license](https://github.com/MMV-Lab/VessQC/blob/main/LICENSE) file. Consider fixing it to be clear about copyright of your code.

Best,
Robert

**Comment by PLampen** [comment]
Hello Robert Haase,

 

Thank you very much for this tip. I was a little confused by these “<<< HEAD”, “===” and “>>> 088ad...” lines. But now I think I have resolved the merge conflict.

 

Best regards

Peter Lampen

 

Von: Robert Haase ***@***.***> 
Gesendet: Donnerstag, 7. November 2024 09:34
An: MMV-Lab/VessQC ***@***.***>
Cc: Peter Lampen ***@***.***>; Mention ***@***.***>
Betreff: [EXT] [MMV-Lab/VessQC] Unclear License (Issue #11)

 

Hi @PLampen <https://github.com/PLampen>  ,

just a minor note: There are some artifacts such as <<< HEAD of a failed git merge in the license <https://github.com/MMV-Lab/VessQC/blob/main/LICENSE>  file. Consider fixing it to be clear about copyright of your code.

Best,
Robert
